# For testing MySQL and PostgreSQL databases
services:
  mysql:
    image: mysql:9.4
    container_name: mysql_proxy_test
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: postgres_proxy_test
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data:rw
    restart: unless-stopped