name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start Docker container
      run: docker compose -f docker-compose.yml up -d
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
        echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
    - name: Test with pytest
      if: matrix.python-version != '3.13'
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        pytest
    - name: Test with pytest +coverage
      if: matrix.python-version == '3.13'
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        pytest --cov=lm_proxy_db_connector --cov-report=xml
    - name: Generate coverage badge
      if: matrix.python-version == '3.13' && (github.event_name == 'push' || github.event_name == 'pull_request')
      uses: tj-actions/coverage-badge-py@v2
      with:
        output: 'coverage.svg'
    - name: Commit coverage badge
      if: matrix.python-version == '3.13' && (github.event_name == 'push' || github.event_name == 'pull_request')
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch origin
        git checkout ${{ github.head_ref || github.ref_name }} --
        git add coverage.svg
        git commit -m "Update coverage badge [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

